---
- name: Обновить список пакетов
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Обновить все пакеты
  apt:
    upgrade: dist

- name: Установить утилиты
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ tools_to_install }}"
  become: yes
